import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Embroidered Lawn Suit - 3PC',
    slug: 'embroidered-lawn-suit-3pc',
    description: 'Beautifully crafted 3-piece embroidered lawn suit.',
    price: 12000,
    discount_price: 8500,
    category: 'Unstitched',
    stock: 50,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Blue'],
    fabric: 'Lawn',
    images: ['https://picsum.photos/seed/dress1/800/1200', 'https://picsum.photos/seed/dress1-back/800/1200'],
    featured: true,
    trending: true,
    is_new: true,
    rating: 4.8,
    created_at: new Date().toISOString()
  },
  {
    id: '2',
    title: 'Silk Collection - Midnight Bloom',
    slug: 'silk-collection-midnight-bloom',
    description: 'Elegant silk dress for formal occasions.',
    price: 15000,
    category: 'Luxury',
    stock: 30,
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Gold'],
    fabric: 'Silk',
    images: ['https://picsum.photos/seed/dress2/800/1200'],
    featured: true,
    trending: false,
    is_new: true,
    rating: 4.9,
    created_at: new Date().toISOString()
  },
  {
    id: '3',
    title: 'Cotton Co-ord Set',
    slug: 'cotton-co-ord-set',
    description: 'Comfortable cotton co-ord set for casual wear.',
    price: 7000,
    discount_price: 5500,
    category: 'Ready to Wear',
    stock: 100,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Yellow', 'Green'],
    fabric: 'Cotton',
    images: ['https://picsum.photos/seed/dress3/800/1200'],
    featured: false,
    trending: true,
    is_new: false,
    rating: 4.5,
    created_at: new Date().toISOString()
  },
  {
    id: '4',
    title: 'Embroidered Velvet Shawl',
    slug: 'embroidered-velvet-shawl',
    description: 'Luxurious velvet shawl with intricate embroidery.',
    price: 15000,
    discount_price: 12000,
    category: 'Accessories',
    stock: 20,
    sizes: ['Free Size'],
    colors: ['Maroon', 'Black'],
    fabric: 'Velvet',
    images: ['https://picsum.photos/seed/shawl1/800/1200'],
    featured: true,
    trending: true,
    is_new: true,
    rating: 5.0,
    created_at: new Date().toISOString()
  }
];
